### ISSUE TITLE
VERSION 1 CHECKOFF - AGLU

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#814]
Verify that

- [x] new data system produces exactly same `aglu` XML files as old data system (see python test results / #954)
```
30 files tested.
0 missing output files.
```
- [x] structure of files matches (see python test results / #954)
``` 0 file discrepancies. ```
- [x] no `temp-data-inject` files still being used (see #917)  ** an aglu `temp-data-inject` is being used in an `OLD_DATA_SYSTEM_BEHAVIOR` block to address #929 this use of `temp-data-inject` is okay for the purposes of version 1 check off. 

- [x] dsr outputs matches gcam 5 outputs (see #932)

- [ ] GCAM runs with these files substituted in

**Comment by kvcalvin** [comment]
@bpbond: some of the files in that list won't exist because we eliminated triplets. Do you want me to update the list?

**Comment by bpbond** [comment]
Yes please!

**Comment by kvcalvin** [comment]
Here is the updated list:

```
batch_ag_cost_IRR_MGMT.xml
batch_ag_Fert_IRR_MGMT.xml
batch_ag_For_Past_bio_base_IRR_MGMT.xml
batch_ag_prodchange_ref_IRR_MGMT.xml
batch_ag_prodchange_ssp1_IRR_MGMT.xml
batch_ag_prodchange_ssp2_IRR_MGMT.xml
batch_ag_prodchange_ssp3_IRR_MGMT.xml
batch_ag_prodchange_ssp4_IRR_MGMT.xml
batch_ag_prodchange_ssp5_IRR_MGMT.xml
batch_ag_water_input_IRR_MGMT.xml
batch_an_input.xml
batch_bio_trade.xml
batch_demand_input.xml
batch_food_SSP1.xml
batch_food_SSP2.xml
batch_food_SSP3.xml
batch_food_SSP4.xml
batch_food_SSP5.xml
batch_land_input_1.xml
batch_land_input_2.xml
batch_land_input_3_IRR.xml
batch_land_input_4_IRR_MGMT.xml
batch_land_input_5_IRR_MGMT.xml
batch_pasture_ssp34.xml
batch_protected_land_input_2.xml
batch_protected_land_input_3.xml
batch_resbio_input_IRR_MGMT.xml
batch_ssp3_bio_trade.xml
batch_ssp4_bio_trade.xml
batch_ssp4_trade.xml
```

**Comment by bpbond** [comment]
Thanks!

**Comment by rplzzz** [comment]
If you're using the XML comparison scripts that I created, the way it works is you point it at an "old" directory that has all the files are supposed to be there, and it looks for them in the "new" directory.  The files in the old directory are taken as a definitive list of the files that are supposed to be in the new output.

@kvcalvin What I recommend you do is find a capable RA and have them go through the check-off criteria one by one.  If the results are correct, then there won't be a lot for them to do.  (If there's a discrepancy, then you may have to enlist additional aid, depending on how hard it is to track down.)  You'll also need to decide what you will want to see in the way of GCAM output to satisfy yourself that results are equivalent.

**Comment by kdorheim** [comment]
@kvcalvin I have a question regarding the list of xmls you posted above. Are these xmls produced by the GCAM 5 data system?

**Comment by kvcalvin** [comment]
They should be.

**Comment by kdorheim** [comment]
@kvcalvin awesome, thanks!

**Comment by kdorheim** [comment]
@bpbond we can go ahead and close this
